import type { Product } from "@/types"

// Mock product data - 30 products total
const products: Product[] = [
  // Floral Category (8 products)
  {
    id: "1",
    name: "Enchanted Bloom",
    description:
      "A captivating floral fragrance with notes of rose, jasmine, and lily of the valley. Perfect for day wear.",
    price: 53990,
    category: "Floral",
    image: "./products/product1.jpg",
    rating: 4.8,
    stock: 15,
    featured: true,
  },
  {
    id: "5",
    name: "Velvet Rose",
    description:
      "A luxurious floral fragrance with notes of Bulgarian rose, peony, and violet. Elegant and sophisticated.",
    price: 57000,
    category: "Floral",
    image: "./products/product2.jpg",
    rating: 4.5,
    stock: 18,
    featured: false,
  },
  {
    id: "9",
    name: "Garden Symphony",
    description: "A delicate blend of white flowers, magnolia, and freesia. Light and romantic for spring days.",
    price: 46800,
    category: "Floral",
    image: "./products/product3.jpg",
    rating: 4.6,
    stock: 22,
    featured: false,
  },
  {
    id: "10",
    name: "Peony Dreams",
    description: "Soft peony petals combined with cherry blossom and white tea. A dreamy feminine scent.",
    price: 49500,
    category: "Floral",
    image: "./products/product4.jpg",
    rating: 4.4,
    stock: 19,
    featured: false,
  },
  {
    id: "11",
    name: "Jasmine Nights",
    description: "Intoxicating jasmine with hints of tuberose and orange blossom. Perfect for evening wear.",
    price: 55200,
    category: "Floral",
    image: "./products/product5.jpg",
    rating: 4.7,
    stock: 14,
    featured: false,
  },
  {
    id: "12",
    name: "Lily Cascade",
    description: "Fresh lily of the valley with green leaves and morning dew. Clean and refreshing.",
    price: 45600,
    category: "Floral",
    image: "./products/product6.jpg",
    rating: 4.3,
    stock: 25,
    featured: false,
  },
  {
    id: "13",
    name: "Rose Garden",
    description: "Classic red roses with hints of geranium and pink pepper. Timeless and elegant.",
    price: 52800,
    category: "Floral",
    image: "./products/product7.jpg",
    rating: 4.6,
    stock: 17,
    featured: false,
  },
  {
    id: "14",
    name: "Violet Whisper",
    description: "Delicate violet leaves with iris and powdery musk. Soft and mysterious.",
    price: 50400,
    category: "Floral",
    image: "./products/product9.jpg",
    rating: 4.2,
    stock: 21,
    featured: false,
  },

  // Woody Category (8 products)
  {
    id: "2",
    name: "Midnight Oud",
    description:
      "A rich and mysterious woody fragrance with notes of oud, sandalwood, and amber. Ideal for evening occasions.",
    price: 72000,
    category: "Woody",
    image: "./products/product10.jpg",
    rating: 4.9,
    stock: 10,
    featured: true,
  },
  {
    id: "6",
    name: "Cedar Whisper",
    description: "A warm woody fragrance with notes of cedar, pine, and vetiver. Perfect for the modern gentleman.",
    price: 51000,
    category: "Woody",
    image: "./products/product11.jpg",
    rating: 4.4,
    stock: 14,
    featured: false,
  },
  {
    id: "15",
    name: "Sandalwood Serenity",
    description: "Creamy sandalwood with vanilla and white musk. Warm and comforting.",
    price: 58800,
    category: "Woody",
    image: "./products/product12.jpg",
    rating: 4.5,
    stock: 16,
    featured: false,
  },
  {
    id: "16",
    name: "Forest Path",
    description: "Deep forest notes with pine, cedar, and moss. Earthy and grounding.",
    price: 54600,
    category: "Woody",
    image: "./products/product13.jpg",
    rating: 4.3,
    stock: 18,
    featured: false,
  },
  {
    id: "17",
    name: "Amber Woods",
    description: "Rich amber with patchouli and dark woods. Sophisticated and intense.",
    price: 69000,
    category: "Woody",
    image: "./products/product14.jpg",
    rating: 4.8,
    stock: 12,
    featured: false,
  },
  {
    id: "18",
    name: "Vetiver Storm",
    description: "Smoky vetiver with black pepper and leather. Bold and masculine.",
    price: 63000,
    category: "Woody",
    image: "./products/product15.jpg",
    rating: 4.6,
    stock: 13,
    featured: false,
  },
  {
    id: "19",
    name: "Birch & Smoke",
    description: "Birch tar with smoky incense and dark chocolate. Mysterious and alluring.",
    price: 64800,
    category: "Woody",
    image: "./products/product16.jpg",
    rating: 4.4,
    stock: 11,
    featured: false,
  },
  {
    id: "20",
    name: "Mahogany Essence",
    description: "Rich mahogany with tobacco and cognac. Luxurious and refined.",
    price: 75000,
    category: "Woody",
    image: "./products/product17.jpg",
    rating: 4.7,
    stock: 9,
    featured: false,
  },

  // Fresh Category (7 products)
  {
    id: "3",
    name: "Ocean Breeze",
    description:
      "A refreshing aquatic scent with notes of sea salt, citrus, and white musk. Perfect for a casual day out.",
    price: 45300,
    category: "Fresh",
    image: "./products/product18.jpg",
    rating: 4.6,
    stock: 20,
    featured: true,
  },
  {
    id: "7",
    name: "Citrus Splash",
    description: "A vibrant fresh fragrance with notes of lemon, bergamot, and neroli. Energizing and uplifting.",
    price: 42000,
    category: "Fresh",
    image: "./products/product8.jpg",
    rating: 4.3,
    stock: 25,
    featured: false,
  },
  {
    id: "21",
    name: "Morning Dew",
    description: "Fresh grass with cucumber and green apple. Clean and invigorating.",
    price: 40800,
    category: "Fresh",
    image: "./products/product19.jpg",
    rating: 4.2,
    stock: 28,
    featured: false,
  },
  {
    id: "22",
    name: "Mint Breeze",
    description: "Cool mint with eucalyptus and lime zest. Refreshing and energetic.",
    price: 43200,
    category: "Fresh",
    image: "./products/product20.jpg",
    rating: 4.4,
    stock: 24,
    featured: false,
  },
  {
    id: "23",
    name: "Aqua Marine",
    description: "Ocean waves with marine algae and sea breeze. Fresh and aquatic.",
    price: 47400,
    category: "Fresh",
    image: "./products/product21.jpg",
    rating: 4.5,
    stock: 22,
    featured: false,
  },
  {
    id: "24",
    name: "Green Tea Zen",
    description: "Japanese green tea with bamboo and white flowers. Peaceful and clean.",
    price: 44400,
    category: "Fresh",
    image: "./products/product22.jpg",
    rating: 4.3,
    stock: 26,
    featured: false,
  },
  {
    id: "25",
    name: "Alpine Air",
    description: "Mountain air with pine needles and snow. Crisp and pure.",
    price: 46200,
    category: "Fresh",
    image: "./products/product9.jpg",
    rating: 4.1,
    stock: 23,
    featured: false,
  },

  // Oriental Category (7 products)
  {
    id: "4",
    name: "Amber Mystique",
    description: "An exotic oriental fragrance with notes of amber, vanilla, and spices. Ideal for special occasions.",
    price: 66000,
    category: "Oriental",
    image: "./products/product24.jpg",
    rating: 4.7,
    stock: 12,
    featured: true,
  },
  {
    id: "8",
    name: "Spice Bazaar",
    description: "A rich oriental fragrance with notes of cinnamon, cardamom, and vanilla. Warm and inviting.",
    price: 63000,
    category: "Oriental",
    image: "./products/product25.jpg",
    rating: 4.6,
    stock: 16,
    featured: false,
  },
  {
    id: "26",
    name: "Golden Sands",
    description: "Warm amber with saffron and rose petals. Luxurious and opulent.",
    price: 70800,
    category: "Oriental",
    image: "./products/product26.jpg",
    rating: 4.8,
    stock: 14,
    featured: false,
  },
  {
    id: "27",
    name: "Silk Road",
    description: "Exotic spices with frankincense and myrrh. Rich and mysterious.",
    price: 67200,
    category: "Oriental",
    image: "./products/product27.jpg",
    rating: 4.5,
    stock: 15,
    featured: false,
  },
  {
    id: "28",
    name: "Vanilla Dreams",
    description: "Madagascar vanilla with tonka bean and caramel. Sweet and comforting.",
    price: 57000,
    category: "Oriental",
    image: "./products/product1.jpg",
    rating: 4.4,
    stock: 19,
    featured: false,
  },
  {
    id: "29",
    name: "Incense Temple",
    description: "Sacred incense with patchouli and dark resins. Spiritual and deep.",
    price: 64800,
    category: "Oriental",
    image: "./products/product5.jpg",
    rating: 4.3,
    stock: 17,
    featured: false,
  },
  {
    id: "30",
    name: "Desert Rose",
    description: "Exotic rose with oud and precious woods. Intense and captivating.",
    price: 81000,
    category: "Oriental",
    image: "./products/product7.jpg",
    rating: 4.9,
    stock: 8,
    featured: false,
  },
]

export async function getProducts(): Promise<Product[]> {
  // In a real application, this would fetch from a database or API
  return products
}

export async function getProductById(id: string): Promise<Product | undefined> {
  // In a real application, this would fetch from a database or API
  return products.find((product) => product.id === id)
}

export async function getProductsByCategory(category: string): Promise<Product[]> {
  // In a real application, this would fetch from a database or API
  return products.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}
